name: app_family_materials
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  single_child_two_dimensional_scroll_view: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PingFangTC
      fonts:
        - asset: fonts/PingFangTC/PingFangTC-Light.otf
        - asset: fonts/PingFangTC/PingFangTC-Regular.otf
        - asset: fonts/PingFangTC/PingFangTC-Medium.otf
        - asset: fonts/PingFangTC/PingFangTC-Semibold.otf
        - asset: fonts/PingFangTC/PingFangTC-Thin.otf
        - asset: fonts/PingFangTC/PingFangTC-Ultralight.otf
    - family: HarmonyOS_Sans
      fonts:
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Black.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Bold.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Light.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Medium.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Regular.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Thin.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Black_Italic.ttf
          style: italic
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Bold_Italic.ttf
          style: italic
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Light_Italic.ttf
          style: italic
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Medium_Italic.ttf
          style: italic
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Regular_Italic.ttf
          style: italic
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Thin_Italic.ttf
          style: italic
        
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
