name: app_family_materials
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  single_child_two_dimensional_scroll_view: ^0.0.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/fonts/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FamilyIcons
      fonts:
        - asset: assets/fonts/FamilyIcons.ttf
    - family: PingFangTC
      fonts:
        - asset: fonts/PingFangTC/PingFang.ttc
    - family: HarmonyOS_Sans
      fonts:
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Bold.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Medium.ttf
        - asset: fonts/HarmonyOS_Sans/HarmonyOS_Sans_Regular.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
