/// Flutter icons FamilyIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FamilyIcons
///      fonts:
///       - asset: fonts/FamilyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FamilyIcons {
  FamilyIcons._();

  static const _kFontFam = 'FamilyIcons';
  static const String _kFontPkg = 'app_family_materials';

  static const IconData star = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
